# Generated by Django 2.0.5 on 2018-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person_DB_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
